name: Build on push

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: var
        name: Setup variables
        run: echo "commit_hash=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/1.21' }}
      - name: Build with Gradle
        run: ./gradlew build
        env:
          POWAH_VERSION: vgit-${{ steps.var.outputs.commit_hash }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: powah ${{ steps.var.outputs.commit_hash }}
          path: build/libs
